name: OCI

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      run: docker login --username mstg --password ${{secrets.DOCKER_SECRET}}
    - name: Build the Docker image
      run: docker build . -t docker.io/mstg/srpmproc:${GITHUB_REF#refs/tags/}
    - name: Push to Docker Hub
      run: docker push docker.io/mstg/srpmproc:${GITHUB_REF#refs/tags/}
