name: OCI

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      run: docker login --username mstg --pasword ${{secrets.DOCKER_SECRET}}
    - name: Get the version
      run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
    - name: Build the Docker image
      run: docker build . -t docker.io/mstg/srpmproc:${SOURCE_TAG}
    - name: Push to Docker Hub
      run: docker push docker.io/mstg/srpmproc:${SOURCE_TAG}
